const robotConfig: Record<string, { text: string; glow: string; scale: number; color: string; rgb: string }> = {
    login: {
        text: "Awaiting credentials...",
        glow: "shadow-[0_0_60px_rgba(var(--color-primary-rgb),0.2)]",
        scale: 1,
        color: "var(--color-primary)",
        rgb: "--color-primary-rgb",
    },
    signup: {
        text: "Initializing new identity...",
        glow: "shadow-[0_0_80px_rgba(var(--color-node-ai-rgb),0.25)]",
        scale: 1.05,
        color: "var(--color-node-ai)",
        rgb: "--color-node-ai-rgb",
    },
    "typing-email": {
        text: "Analyzing email pattern...",
        glow: "shadow-[0_0_80px_rgba(var(--color-primary-rgb),0.3)]",
        scale: 1.03,
        color: "var(--color-primary)",
        rgb: "--color-primary-rgb",
    },
    "typing-name": {
        text: "Verifying identity format...",
        glow: "shadow-[0_0_80px_rgba(var(--color-node-user-rgb),0.3)]",
        scale: 1.03,
        color: "var(--color-node-user)",
        rgb: "--color-node-user-rgb",
    },
    "typing-password": {
        text: "Encrypting credentials...",
        glow: "shadow-[0_0_80px_rgba(var(--color-node-frozen-rgb),0.3)]",
        scale: 1.02,
        color: "var(--color-node-frozen)",
        rgb: "--color-node-frozen-rgb",
    },
    "forgot-password": {
        text: "Searching recovery routes...",
        glow: "shadow-[0_0_60px_rgba(var(--color-node-user-rgb),0.2)]",
        scale: 1,
        color: "var(--color-node-user)",
        rgb: "--color-node-user-rgb",
    },
    "reset-password": {
        text: "Ready for new security key...",
        glow: "shadow-[0_0_80px_rgba(var(--color-node-frozen-rgb),0.3)]",
        scale: 1.02,
        color: "var(--color-node-frozen)",
        rgb: "--color-node-frozen-rgb",
    },
    otp: {
        text: "Awaiting security token...",
        glow: "shadow-[0_0_80px_rgba(var(--color-node-active-rgb),0.3)]",
        scale: 1.04,
        color: "var(--color-node-active)",
        rgb: "--color-node-active-rgb",
    },
    passkey: {
        text: "Scanning biometric passkey...",
        glow: "shadow-[0_0_80px_rgba(var(--color-node-ai-rgb),0.3)]",
        scale: 1.05,
        color: "var(--color-node-ai)",
        rgb: "--color-node-ai-rgb",
    },
    "user-exists": {
        text: "Identity collision detected.",
        glow: "shadow-[0_0_80px_rgba(var(--color-node-deleted-rgb),0.3)]",
        scale: 1,
        color: "var(--color-node-deleted)",
        rgb: "--color-node-deleted-rgb",
    },
    "email-sent": {
        text: "Courier dispatched securely.",
        glow: "shadow-[0_0_80px_rgba(var(--color-node-active-rgb),0.3)]",
        scale: 1.05,
        color: "var(--color-node-active)",
        rgb: "--color-node-active-rgb",
    },
    success: {
        text: "Access granted.",
        glow: "shadow-[0_0_100px_rgba(var(--color-node-ai-rgb),0.4)]",
        scale: 1.08,
        color: "var(--color-node-ai)",
        rgb: "--color-node-ai-rgb",
    },
    error: {
        text: "Authentication failed.",
        glow: "shadow-[0_0_100px_rgba(var(--color-node-deleted-rgb),0.4)]",
        scale: 0.95,
        color: "var(--color-node-deleted)",
        rgb: "--color-node-deleted-rgb",
    },
    idle: {
        text: "Listening for context...",
        glow: "shadow-[0_0_60px_rgba(var(--color-primary-rgb),0.15)]",
        scale: 1,
        color: "var(--color-primary)",
        rgb: "--color-primary-rgb",
    },
};

export default robotConfig;