"""initial commit

Revision ID: a990a5848fb0
Revises: 
Create Date: 2026-03-01 14:47:28.955657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a990a5848fb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # auth_type is non-null in model; give existing rows a default before removing it
    op.add_column('users', sa.Column('auth_type', sa.String(), nullable=False, server_default='password'))
    # remove server_default after population if desired
    op.alter_column('users', 'auth_type', server_default=None)
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'auth_type')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###
